# Static Storage Provisioning for Prometheus/Grafana
# 
# APPROACH: Static provisioning with node-pinned local storage
# - Pre-created PVs with hostPath storage on at-compute010:/mnt/md0/k8s_apps/
# - StorageClass uses no-provisioner (no dynamic allocation)
# - Pods constrained to at-compute010 via nodeSelector for storage access
#
# BENEFITS: Fast local SSD/RAID storage, predictable performance
# LIMITATIONS: Single node dependency, no automatic failover


# Create a PersistentVolume for Prometheus
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-atcompute010
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: prometheus-storage
  hostPath:
    # need to also do: sudo chown -R 1000:2000 /mnt/md0/k8s_apps/prometheus since prometheus runs with user 1000 and group id 2000
    path: "/mnt/md0/k8s_apps/prometheus"
    type: DirectoryOrCreate

# Create a PersistentVolume for Grafana
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-atcompute010
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: grafana-storage  # Custom storage class name
  hostPath:
    path: "/mnt/md0/k8s_apps/grafana"
    type: DirectoryOrCreate
  
# Create StorageClass for Prometheus and Grafana
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prometheus-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate # ensures the volumes are bound immediately when persistent volume claims are created, as opposed to waiting for a pod to be scheduled
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: grafana-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate