apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alert-rules-test
  namespace: monitoring  # adjust to your grafana namespace
  labels:
    grafana_alert: "1"
data:
  alert-rules.yaml: |
    apiVersion: 1
    groups:
        - orgId: 1
          name: 10s-eval
          folder: Advanced
          interval: 10s
          rules:
            - uid: aeyw1nust9reob
              title: test-alert
              condition: C
              data:
                - refId: A
                  relativeTimeRange:
                    from: 600
                    to: 0
                  datasourceUid: prometheus
                  model:
                    editorMode: code
                    expr: (  1 - (    max(node_filesystem_avail_bytes{device="//at-storageB1.stanford.edu/M", fstype="cifs"}) / max(node_filesystem_size_bytes{device="//at-storageB1.stanford.edu/M", fstype="cifs"})  )) * 100
                    instant: true
                    intervalMs: 1000
                    legendFormat: __auto
                    maxDataPoints: 43200
                    range: false
                    refId: A
                - refId: C
                  datasourceUid: __expr__
                  model:
                    conditions:
                        - evaluator:
                            params:
                                - 5
                            type: gt
                          operator:
                            type: and
                          query:
                            params:
                                - C
                          reducer:
                            params: []
                            type: last
                          type: query
                    datasource:
                        type: __expr__
                        uid: __expr__
                    expression: A
                    intervalMs: 1000
                    maxDataPoints: 43200
                    refId: C
                    type: threshold
              noDataState: NoData
              execErrState: Error
              for: 10s
              isPaused: false
              notification_settings:
                receiver: enigma-slack-k8s-alerts
