apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alert-rules-test
  namespace: monitoring  # adjust to your grafana namespace
  labels:
    grafana_alert: "1"
data:
  alert-rules.yaml: |
    apiVersion: 1
    groups:
        - orgId: 1
          name: 1h
          folder: Alerts
          interval: 1h
          rules:
            - uid: aeyp1u9wiy1vkc
              title: nvidia-device-plugin-daemonset
              condition: C
              data:
                - refId: A
                  relativeTimeRange:
                    from: 600
                    to: 0
                  datasourceUid: prometheus
                  model:
                    editorMode: code
                    expr: (label_replace(kube_node_status_capacity{resource="nvidia_com_gpu"}, "Hostname", "$1", "node", "(.*)") != on(Hostname) count by (Hostname) (DCGM_FI_DEV_GPU_UTIL))
                    instant: true
                    intervalMs: 1000
                    legendFormat: __auto
                    maxDataPoints: 43200
                    range: false
                    refId: A
                - refId: C
                  datasourceUid: __expr__
                  model:
                    conditions:
                        - evaluator:
                            params:
                                - 0
                            type: gt
                          operator:
                            type: and
                          query:
                            params:
                                - C
                          reducer:
                            params: []
                            type: last
                          type: query
                    datasource:
                        type: __expr__
                        uid: __expr__
                    expression: A
                    intervalMs: 1000
                    maxDataPoints: 43200
                    refId: C
                    type: threshold
              noDataState: NoData
              execErrState: Error
              for: 1h
              annotations:
                summary: Use 'kubectl describe node <node-name>' to confirm that kubernetes thinks there are fewer GPUs than expected, where expected is determined by DCGM_FI_DEV_GPU_UTIL from the nvidia-dcgm-exporter pod on that node. To fix, restart nvidia-device-plugin-daemonset pod on affected node.
              isPaused: false
              notification_settings:
                receiver: enigma-slack-k8s-alerts
            - uid: beyp2wfg8fbi8e
              title: at-storageB1_M
              condition: C
              data:
                - refId: A
                  relativeTimeRange:
                    from: 600
                    to: 0
                  datasourceUid: prometheus
                  model:
                    editorMode: code
                    expr: "(\n  1 - (\n    max(node_filesystem_avail_bytes{device=\"//at-storageB1.stanford.edu/M\", fstype=\"cifs\"})\n    / \n    max(node_filesystem_size_bytes{device=\"//at-storageB1.stanford.edu/M\", fstype=\"cifs\"})\n  )\n) * 100"
                    instant: true
                    intervalMs: 1000
                    legendFormat: __auto
                    maxDataPoints: 43200
                    range: false
                    refId: A
                - refId: C
                  datasourceUid: __expr__
                  model:
                    conditions:
                        - evaluator:
                            params:
                                - 2
                            type: gt
                          operator:
                            type: and
                          query:
                            params:
                                - C
                          reducer:
                            params: []
                            type: last
                          type: query
                    datasource:
                        type: __expr__
                        uid: __expr__
                    expression: A
                    intervalMs: 1000
                    maxDataPoints: 43200
                    refId: C
                    type: threshold
              noDataState: NoData
              execErrState: Error
              for: 1h
              isPaused: false
              notification_settings:
                receiver: enigma-slack-k8s-alerts 
