{
 "title": "Resource Allocation",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Hostname",
    "query": {
     "query": "label_values(DCGM_FI_DEV_FB_USED,Hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource requests and limits (cluster-wide)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 641 },
     "targets": [
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{resource=\"cpu\"}\n* on(pod, namespace) \ngroup_left() \n(kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"cpu\"})",
       "legendFormat": "cpu requests"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{resource=\"cpu\"}\n* on(pod, namespace) \ngroup_left() \n(kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"cpu\"})",
       "legendFormat": "cpu limits"
      }
     ]
    },
    {
     "title": "GPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 641 },
     "targets": [
      {
       "expr": "# Percentage of total cluster GPUs requested by running pods\nsum(\n    kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
       "legendFormat": "gpu requests"
      },
      {
       "expr": "# Percentage of total cluster GPUs requested by running pods\nsum(\n    kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
       "legendFormat": "gpu limits"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 641 },
     "targets": [
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{resource=\"memory\"}\n* on(pod, namespace) \ngroup_left() \n(kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"memory\"})",
       "legendFormat": "memory requests"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{resource=\"memory\"}\n* on(pod, namespace) \ngroup_left() \n(kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"memory\"})",
       "legendFormat": "memory limits"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource requests (by node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fraction CPUs requested",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "(\n  sum by(node) (\n    kube_pod_container_resource_requests{resource=\"cpu\"}\n    * on(pod, namespace) \n    group_left(node) \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n  ) / on(node) group_left() sum by(node) (kube_node_status_capacity{resource=\"cpu\"})\n) or (\n  0 * sum by(node) (kube_node_status_capacity{resource=\"cpu\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Fraction Memory requested",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 560 },
     "targets": [
      {
       "expr": "(\n  sum by(node) (\n    kube_pod_container_resource_requests{resource=\"memory\"}\n    * on(pod, namespace) \n    group_left(node) \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n  ) / on(node) group_left() sum by(node) (kube_node_status_capacity{resource=\"memory\"})\n) or (\n  0 * sum by(node) (kube_node_status_capacity{resource=\"memory\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Fraction GPUs requested",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 569 },
     "targets": [
      {
       "expr": "(\n  sum by(node) (\n    kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}\n    * on(pod, namespace) \n    group_left(node) \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n  ) \n  / \n  on(node) group_left() sum by(node) (kube_node_status_capacity{resource=\"nvidia_com_gpu\"})\n) or (\n  0 * sum by(node) (kube_node_status_capacity{resource=\"nvidia_com_gpu\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource limits (by node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fraction CPU limits",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 706 },
     "targets": [
      {
       "expr": "(\n  sum by(node) (\n    kube_pod_container_resource_limits{resource=\"cpu\"}\n    * on(pod, namespace) \n    group_left(node) \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n  ) / on(node) group_left() sum by(node) (kube_node_status_capacity{resource=\"cpu\"})\n) or (\n  0 * sum by(node) (kube_node_status_capacity{resource=\"cpu\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Fraction Memory limits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 715 },
     "targets": [
      {
       "expr": "(\n  sum by(node) (\n    kube_pod_container_resource_limits{resource=\"memory\"}\n    * on(pod, namespace) \n    group_left(node) \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n  ) / on(node) group_left() sum by(node) (kube_node_status_capacity{resource=\"memory\"})\n) or (\n  0 * sum by(node) (kube_node_status_capacity{resource=\"memory\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Fraction GPU limits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 723 },
     "targets": [
      {
       "expr": "(\n  sum by(node) (\n    kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\"}\n    * on(pod, namespace) \n    group_left(node) \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n  ) \n  / \n  on(node) group_left() sum by(node) (kube_node_status_capacity{resource=\"nvidia_com_gpu\"})\n) or (\n  0 * sum by(node) (kube_node_status_capacity{resource=\"nvidia_com_gpu\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource requests and limits (by namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 650 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n    kube_pod_container_resource_requests{resource=\"cpu\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n) / scalar(sum(kube_node_status_capacity{resource=\"cpu\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU limits by namespace",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 9, "y": 650 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n    kube_pod_container_resource_limits{resource=\"cpu\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n) / scalar(sum(kube_node_status_capacity{resource=\"cpu\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 659 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n    kube_pod_container_resource_requests{resource=\"memory\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n) / scalar(sum(kube_node_status_capacity{resource=\"memory\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory limits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 9, "y": 659 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n    kube_pod_container_resource_limits{resource=\"memory\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n) / scalar(sum(kube_node_status_capacity{resource=\"memory\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 667 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n    kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n) / scalar(sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU limits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 9, "y": 667 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n    kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n) / scalar(sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Utilization vs requests (by namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage / requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n  rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\"}[1m])\n  * on(pod, namespace) group_left()\n  (kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum by(namespace) (\n  kube_pod_container_resource_requests{resource=\"cpu\"}\n  * on(pod, namespace) group_left()\n  (kube_pod_status_phase{phase=\"Running\"} == 1)\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory usage / requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n  container_memory_working_set_bytes{container!=\"\",container!=\"POD\"}\n  * on(pod, namespace) group_left()\n  (kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum by(namespace) (\n  kube_pod_container_resource_requests{resource=\"memory\"}\n  * on(pod, namespace) group_left()\n  (kube_pod_status_phase{phase=\"Running\"} == 1)\n) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU utilization / requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 15, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n  label_replace(\n    sum by(node, namespace) (\n      kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}\n    ),\n    \"Hostname\", \"$1\", \"node\", \"(.*)\"\n  )\n  * on(Hostname) group_left()\n  avg by(Hostname) (DCGM_FI_DEV_GPU_UTIL)\n)\n/\nsum by(namespace) (\n  kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}\n) / 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}