{
 "title": "Temperature",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Max GPU core temp (C)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by(Hostname) (DCGM_FI_DEV_GPU_TEMP)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU memory temp (C)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by(Hostname) (DCGM_FI_DEV_MEMORY_TEMP)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max CPU temp (C)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by(nodename) (\n  node_hwmon_temp_celsius{chip=~\".*coretemp.*\"}\n  * on(instance) \n  group_left(nodename) \n  node_uname_info\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}