{
 "title": "Utilization",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Hostname",
    "query": {
     "query": "label_values(DCGM_FI_DEV_FB_USED,Hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU utilization: not idle",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "100 - avg by(nodename) (\n  rate(node_cpu_seconds_total{mode=\"idle\"}[1m])\n  * on(instance) \n  group_left(nodename) \n  node_uname_info\n) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU utilization: not idle",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 9, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - avg by(nodename) (\n  rate(node_cpu_seconds_total{mode=\"idle\"}[1m])\n  * on(instance) \n  group_left(nodename) \n  node_uname_info\n) * 100",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "CPU utilization: user space usage",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 5, "x": 9, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(nodename) (irate(node_cpu_seconds_total{mode=\"user\"}[1m]) \n* on(instance) group_left(nodename) node_uname_info) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU utilization: system usage",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 5, "x": 14, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(nodename) (irate(node_cpu_seconds_total{mode=\"system\"}[1m]) \n* on(instance) group_left(nodename) node_uname_info) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU utilization: I/O wait",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 5, "x": 19, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(nodename) (irate(node_cpu_seconds_total{mode=\"iowait\"}[1m]) \n* on(instance) group_left(nodename) node_uname_info) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU utilization",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 14, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_GPU_UTIL)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Power draw",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total power draw per node",
     "type": "timeseries",
     "description": "2500w per server",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "sum(DCGM_FI_DEV_POWER_USAGE) by (Hostname)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max power draw per node",
     "type": "timeseries",
     "description": "max 350w per slot",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "max by(Hostname) (DCGM_FI_DEV_POWER_USAGE)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total power draw across nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 177 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "sum(DCGM_FI_DEV_POWER_USAGE) by (Hostname)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Memory used per node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes\n* on(instance) group_left(nodename) (node_uname_info)",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "GPU memory utilization (node :: gpu)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 105 },
     "repeat": "Hostname",
     "targets": [
      {
       "expr": "max(DCGM_FI_DEV_FB_USED{Hostname=\"$Hostname\"}) by (Hostname, gpu) \n/ \n(max(DCGM_FI_DEV_FB_USED{Hostname=\"$Hostname\"}) by (Hostname, gpu)  + max(DCGM_FI_DEV_FB_FREE{Hostname=\"$Hostname\"}) by (Hostname, gpu))",
       "legendFormat": "{{Hostname}} :: gpu{{gpu}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System daemons",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "kubelet system daemons CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum by (instance) (rate(container_cpu_usage_seconds_total{id=~\"/system.slice/(kubelet|containerd).service\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kubelet system daemons memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(container_memory_usage_bytes{id=~\"/system.slice/(kubelet|containerd).service\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IO (WIP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "New panel",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 212 },
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total{job=\"node-exporter\"}[5m]) * on(instance) group_left(nodename) node_uname_info",
       "legendFormat": "{{nodename}} :: {{device}}"
      }
     ]
    }
   ]
  }
 ]
}