{
 "title": "Usage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Hostname",
    "query": {
     "query": "label_values(DCGM_FI_DEV_FB_USED,Hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Utilization vs requests (by namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage / requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n  rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\"}[1m])\n  * on(pod, namespace) group_left()\n  (kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum by(namespace) (\n  kube_pod_container_resource_requests{resource=\"cpu\"}\n  * on(pod, namespace) group_left()\n  (kube_pod_status_phase{phase=\"Running\"} == 1)\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory usage / requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 99 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n  container_memory_working_set_bytes{container!=\"\",container!=\"POD\"}\n  * on(pod, namespace) group_left()\n  (kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum by(namespace) (\n  kube_pod_container_resource_requests{resource=\"memory\"}\n  * on(pod, namespace) group_left()\n  (kube_pod_status_phase{phase=\"Running\"} == 1)\n) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU utilization / requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 15, "x": 0, "y": 107 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n  label_replace(\n    sum by(node, namespace) (\n      kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}\n    ),\n    \"Hostname\", \"$1\", \"node\", \"(.*)\"\n  )\n  * on(Hostname) group_left()\n  avg by(Hostname) (DCGM_FI_DEV_GPU_UTIL)\n)\n/\nsum by(namespace) (\n  kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}\n) / 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource requests (by node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU requests by node",
     "type": "bargauge",
     "gridPos": { "h": 32, "w": 7, "x": 0, "y": 235 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum by(node) (\n    kube_pod_container_resource_requests{resource=\"cpu\"}\n    * on(pod, namespace) \n    group_left(node) \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n  ) / on(node) group_left() sum by(node) (kube_node_status_capacity{resource=\"cpu\"})\n) or (\n  0 * sum by(node) (kube_node_status_capacity{resource=\"cpu\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory requests",
     "type": "bargauge",
     "gridPos": { "h": 32, "w": 7, "x": 7, "y": 235 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum by(node) (\n    kube_pod_container_resource_requests{resource=\"memory\"}\n    * on(pod, namespace) \n    group_left(node) \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n  ) / on(node) group_left() sum by(node) (kube_node_status_capacity{resource=\"memory\"})\n) or (\n  0 * sum by(node) (kube_node_status_capacity{resource=\"memory\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU requests",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 7, "x": 14, "y": 235 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum by(node) (\n    kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}\n    * on(pod, namespace) \n    group_left(node) \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n  ) \n  / \n  on(node) group_left() sum by(node) (kube_node_status_capacity{resource=\"nvidia_com_gpu\"})\n) or (\n  0 * sum by(node) (kube_node_status_capacity{resource=\"nvidia_com_gpu\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource requests and limits (cluster-wide)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 233 },
     "targets": [
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{resource=\"cpu\"}\n* on(pod, namespace) \ngroup_left() \n(kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"cpu\"})",
       "legendFormat": "cpu requests"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{resource=\"cpu\"}\n* on(pod, namespace) \ngroup_left() \n(kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"cpu\"})",
       "legendFormat": "cpu limits"
      }
     ]
    },
    {
     "title": "GPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 233 },
     "targets": [
      {
       "expr": "# Percentage of total cluster GPUs requested by running pods\nsum(\n    kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
       "legendFormat": "gpu requests"
      },
      {
       "expr": "# Percentage of total cluster GPUs requested by running pods\nsum(\n    kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
       "legendFormat": "gpu limits"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 233 },
     "targets": [
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{resource=\"memory\"}\n* on(pod, namespace) \ngroup_left() \n(kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"memory\"})",
       "legendFormat": "memory requests"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{resource=\"memory\"}\n* on(pod, namespace) \ngroup_left() \n(kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"memory\"})",
       "legendFormat": "memory limits"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource requests and limits (by namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 234 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n    kube_pod_container_resource_requests{resource=\"cpu\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n) / scalar(sum(kube_node_status_capacity{resource=\"cpu\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU limits by namespace",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 9, "y": 234 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n    kube_pod_container_resource_limits{resource=\"cpu\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n) / scalar(sum(kube_node_status_capacity{resource=\"cpu\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 290 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n    kube_pod_container_resource_requests{resource=\"memory\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n) / scalar(sum(kube_node_status_capacity{resource=\"memory\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory limits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 9, "y": 290 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n    kube_pod_container_resource_limits{resource=\"memory\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n) / scalar(sum(kube_node_status_capacity{resource=\"memory\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 298 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n    kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n) / scalar(sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU limits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 9, "y": 298 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n    kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n) / scalar(sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource limits (by node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU limits",
     "type": "bargauge",
     "gridPos": { "h": 30, "w": 6, "x": 0, "y": 385 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum by(node) (\n    kube_pod_container_resource_limits{resource=\"cpu\"}\n    * on(pod, namespace) \n    group_left(node) \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n  ) / on(node) group_left() sum by(node) (kube_node_status_capacity{resource=\"cpu\"})\n) or (\n  0 * sum by(node) (kube_node_status_capacity{resource=\"cpu\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory limits",
     "type": "bargauge",
     "gridPos": { "h": 30, "w": 6, "x": 6, "y": 385 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum by(node) (\n    kube_pod_container_resource_limits{resource=\"memory\"}\n    * on(pod, namespace) \n    group_left(node) \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n  ) / on(node) group_left() sum by(node) (kube_node_status_capacity{resource=\"memory\"})\n) or (\n  0 * sum by(node) (kube_node_status_capacity{resource=\"memory\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU limits",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 7, "x": 12, "y": 385 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum by(node) (\n    kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\"}\n    * on(pod, namespace) \n    group_left(node) \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n  ) \n  / \n  on(node) group_left() sum by(node) (kube_node_status_capacity{resource=\"nvidia_com_gpu\"})\n) or (\n  0 * sum by(node) (kube_node_status_capacity{resource=\"nvidia_com_gpu\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU utilization: not idle",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 9, "x": 0, "y": 237 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - avg by(nodename) (\n  rate(node_cpu_seconds_total{mode=\"idle\"}[1m])\n  * on(instance) \n  group_left(nodename) \n  node_uname_info\n) * 100",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "CPU utilization: user space usage",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 5, "x": 9, "y": 237 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(nodename) (irate(node_cpu_seconds_total{mode=\"user\"}[1m]) \n* on(instance) group_left(nodename) node_uname_info) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU utilization: system usage",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 5, "x": 14, "y": 237 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(nodename) (irate(node_cpu_seconds_total{mode=\"system\"}[1m]) \n* on(instance) group_left(nodename) node_uname_info) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU utilization: I/O wait",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 5, "x": 19, "y": 237 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(nodename) (irate(node_cpu_seconds_total{mode=\"iowait\"}[1m]) \n* on(instance) group_left(nodename) node_uname_info) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU utilization",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_GPU_UTIL)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total power draw per node",
     "type": "timeseries",
     "description": "2500w per server",
     "gridPos": { "h": 8, "w": 12, "x": 1, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "sum(DCGM_FI_DEV_POWER_USAGE) by (Hostname)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max power draw per node",
     "type": "timeseries",
     "description": "max 350w per slot",
     "gridPos": { "h": 8, "w": 9, "x": 13, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "max by(Hostname) (DCGM_FI_DEV_POWER_USAGE)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total power draw across nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 1, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "sum(DCGM_FI_DEV_POWER_USAGE) by (Hostname)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Memory used per node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes\n* on(instance) group_left(nodename) (node_uname_info)",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "GPU memory utilization (node :: gpu)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
     "repeat": "Hostname",
     "targets": [
      {
       "expr": "max(DCGM_FI_DEV_FB_USED{Hostname=\"$Hostname\"}) by (Hostname, gpu) \n/ \n(max(DCGM_FI_DEV_FB_USED{Hostname=\"$Hostname\"}) by (Hostname, gpu)  + max(DCGM_FI_DEV_FB_FREE{Hostname=\"$Hostname\"}) by (Hostname, gpu))",
       "legendFormat": "{{Hostname}} :: gpu{{gpu}}"
      }
     ]
    }
   ]
  }
 ]
}