{
 "title": "Usage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Resource requests and limits (cluster-wide)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{resource=\"cpu\"}\n* on(pod, namespace) \ngroup_left() \n(kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"cpu\"})",
       "legendFormat": "cpu requests"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{resource=\"cpu\"}\n* on(pod, namespace) \ngroup_left() \n(kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"cpu\"})",
       "legendFormat": "cpu limits"
      }
     ]
    },
    {
     "title": "GPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "targets": [
      {
       "expr": "# Percentage of total cluster GPUs requested by running pods\nsum(\n    kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
       "legendFormat": "gpu requests"
      },
      {
       "expr": "# Percentage of total cluster GPUs requested by running pods\nsum(\n    kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})",
       "legendFormat": "gpu limits"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum(\n    kube_pod_container_resource_requests{resource=\"memory\"}\n* on(pod, namespace) \ngroup_left() \n(kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"memory\"})",
       "legendFormat": "memory requests"
      },
      {
       "expr": "sum(\n    kube_pod_container_resource_limits{resource=\"memory\"}\n* on(pod, namespace) \ngroup_left() \n(kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"memory\"})",
       "legendFormat": "memory limits"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource requests and limits (by namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n    kube_pod_container_resource_requests{resource=\"cpu\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n) / scalar(sum(kube_node_status_capacity{resource=\"cpu\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU limits by namespace",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 9, "y": 2 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n    kube_pod_container_resource_limits{resource=\"cpu\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n) / scalar(sum(kube_node_status_capacity{resource=\"cpu\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n    kube_pod_container_resource_requests{resource=\"memory\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n) / scalar(sum(kube_node_status_capacity{resource=\"memory\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory limits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 9, "y": 11 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n    kube_pod_container_resource_limits{resource=\"memory\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n) / scalar(sum(kube_node_status_capacity{resource=\"memory\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n    kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n) / scalar(sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU limits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 9, "y": 19 },
     "targets": [
      {
       "expr": "sum by(namespace) (\n    kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n) / scalar(sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"}))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource requests (by node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU requests by node",
     "type": "bargauge",
     "gridPos": { "h": 32, "w": 7, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum by(node) (\n    kube_pod_container_resource_requests{resource=\"cpu\"}\n    * on(pod, namespace) \n    group_left(node) \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n  ) / on(node) group_left() sum by(node) (kube_node_status_capacity{resource=\"cpu\"})\n) or (\n  0 * sum by(node) (kube_node_status_capacity{resource=\"cpu\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory requests",
     "type": "bargauge",
     "gridPos": { "h": 32, "w": 7, "x": 7, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum by(node) (\n    kube_pod_container_resource_requests{resource=\"memory\"}\n    * on(pod, namespace) \n    group_left(node) \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n  ) / on(node) group_left() sum by(node) (kube_node_status_capacity{resource=\"memory\"})\n) or (\n  0 * sum by(node) (kube_node_status_capacity{resource=\"memory\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU requests",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 7, "x": 14, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum by(node) (\n    kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}\n    * on(pod, namespace) \n    group_left(node) \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n  ) \n  / \n  on(node) group_left() sum by(node) (kube_node_status_capacity{resource=\"nvidia_com_gpu\"})\n) or (\n  0 * sum by(node) (kube_node_status_capacity{resource=\"nvidia_com_gpu\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource limits (by node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU limits",
     "type": "bargauge",
     "gridPos": { "h": 30, "w": 6, "x": 0, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum by(node) (\n    kube_pod_container_resource_limits{resource=\"cpu\"}\n    * on(pod, namespace) \n    group_left(node) \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n  ) / on(node) group_left() sum by(node) (kube_node_status_capacity{resource=\"cpu\"})\n) or (\n  0 * sum by(node) (kube_node_status_capacity{resource=\"cpu\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory limits",
     "type": "bargauge",
     "gridPos": { "h": 30, "w": 6, "x": 6, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum by(node) (\n    kube_pod_container_resource_limits{resource=\"memory\"}\n    * on(pod, namespace) \n    group_left(node) \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n  ) / on(node) group_left() sum by(node) (kube_node_status_capacity{resource=\"memory\"})\n) or (\n  0 * sum by(node) (kube_node_status_capacity{resource=\"memory\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU limits",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 7, "x": 12, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n  sum by(node) (\n    kube_pod_container_resource_limits{resource=\"nvidia_com_gpu\"}\n    * on(pod, namespace) \n    group_left(node) \n    (kube_pod_info * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"} == 1))\n  ) \n  / \n  on(node) group_left() sum by(node) (kube_node_status_capacity{resource=\"nvidia_com_gpu\"})\n) or (\n  0 * sum by(node) (kube_node_status_capacity{resource=\"nvidia_com_gpu\"})\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU utilization: not idle",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 9, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - avg by(nodename) (\n  rate(node_cpu_seconds_total{mode=\"idle\"}[1m])\n  * on(instance) \n  group_left(nodename) \n  node_uname_info\n) * 100",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "CPU utilization: user space usage",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 5, "x": 9, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(nodename) (irate(node_cpu_seconds_total{mode=\"user\"}[1m]) \n* on(instance) group_left(nodename) node_uname_info) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU utilization: system usage",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 5, "x": 14, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(nodename) (irate(node_cpu_seconds_total{mode=\"system\"}[1m]) \n* on(instance) group_left(nodename) node_uname_info) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU utilization: I/O wait",
     "type": "bargauge",
     "gridPos": { "h": 15, "w": 5, "x": 19, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(nodename) (irate(node_cpu_seconds_total{mode=\"iowait\"}[1m]) \n* on(instance) group_left(nodename) node_uname_info) * 100",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU utilization",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 627 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(Hostname) (DCGM_FI_DEV_GPU_UTIL)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}