{
 "title": "Cluster Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Kubernetes API server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"apiserver\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"true\"}==1)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"false\"}==1)",
     "legendFormat": "NotReady"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"unknown\"}==1)",
     "legendFormat": "Unknown"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable)",
     "legendFormat": "Unschedulable"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Succeeded\"})",
     "legendFormat": "Succeeded"
    }
   ]
  },
  {
   "title": "Pods per node",
   "type": "stat",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(node) (\n  kube_pod_info \n  * on(pod, namespace) \n  group_left() \n  (kube_pod_status_phase{phase=\"Running\"} == 1)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 memory-consuming (GB) containers",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, container_memory_usage_bytes) / 1024^3",
     "legendFormat": "{{namespace}} :: {{pod}}"
    }
   ]
  },
  {
   "title": "Top 10 CPU-consuming containers",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 8, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, \n rate(container_cpu_usage_seconds_total[5m])\n * on(pod, namespace) \n group_left() \n (kube_pod_status_phase{phase=\"Running\"} == 1)\n)",
     "legendFormat": "{{namespace}} :: {{pod}}"
    }
   ]
  },
  {
   "title": "resource vs capacity fraction",
   "type": "stat",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{resource=\"cpu\"}\n* on(pod, namespace) \ngroup_left() \n(kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"cpu\"})",
     "legendFormat": "cpu requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{resource=\"cpu\"}\n* on(pod, namespace) \ngroup_left() \n(kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"cpu\"})",
     "legendFormat": "cpu limits"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{resource=\"memory\"}\n* on(pod, namespace) \ngroup_left() \n(kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"memory\"})",
     "legendFormat": "mem requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{resource=\"memory\"}\n* on(pod, namespace) \ngroup_left() \n(kube_pod_status_phase{phase=\"Running\"} == 1)\n) / sum(kube_node_status_capacity{resource=\"memory\"})",
     "legendFormat": "mem limits"
    }
   ]
  },
  {
   "title": "CPU requests vs capacity",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 8, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by(node) (\n    kube_pod_container_resource_requests{resource=\"cpu\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_status_phase{phase=\"Running\"} == 1)\n    * on(pod, namespace)\n    group_left(node)\n    kube_pod_info\n  )\n) \n/ \non(node) \n(\n  kube_node_status_capacity{resource=\"cpu\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU limits vs capacity",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 9, "x": 8, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by(node) (\n    kube_pod_container_resource_limits{resource=\"cpu\"}\n    * on(pod, namespace) \n    group_left() \n    (kube_pod_status_phase{phase=\"Running\"} == 1)\n    * on(pod, namespace)\n    group_left(node)\n    kube_pod_info\n  )\n) \n/ \non(node) \n(\n  kube_node_status_capacity{resource=\"cpu\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}