{
 "title": "Storage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "CIFS/Network drives", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Proportion used",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1- (node_filesystem_avail_bytes{fstype=\"cifs\"}\n* on(instance) \ngroup_left(nodename) \nnode_uname_info{nodename=\"at-compute010\"}) \n/ \n(node_filesystem_size_bytes{fstype=\"cifs\"}\n* on(instance) \ngroup_left(nodename) \nnode_uname_info{nodename=\"at-compute010\"})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Total size (TB)",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 10, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype=\"cifs\"}\n* on(instance) \ngroup_left(nodename) \nnode_uname_info{nodename=\"at-compute010\"}) / 1024^4",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Node storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "/mnt/md0 proportion used",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{mountpoint=\"/mnt/md0\"}\n* on(instance) \ngroup_left(nodename) \nnode_uname_info) \n/ \n(node_filesystem_size_bytes{mountpoint=\"/mnt/md0\"}\n* on(instance) \ngroup_left(nodename) \nnode_uname_info)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Root \"/\"",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{mountpoint=\"/\"}\n* on(instance) \ngroup_left(nodename) \nnode_uname_info) \n/ \n(node_filesystem_size_bytes{mountpoint=\"/\"}\n* on(instance) \ngroup_left(nodename) \nnode_uname_info)",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "/mnt/md0 total size (GB)",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/mnt/md0\"}\n* on(instance) \ngroup_left(nodename) \nnode_uname_info) / 1024^3",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Root \"/\" total size (GB)",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\"}\n* on(instance) \ngroup_left(nodename) \nnode_uname_info) / 1024^3",
     "legendFormat": "{{nodename}}"
    }
   ]
  }
 ]
}