{
 "title": "Utilization",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU utilization: not idle",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - avg by(nodename) (\n  rate(node_cpu_seconds_total{mode=\"idle\"}[1m])\n  * on(instance) \n  group_left(nodename) \n  node_uname_info\n) * 100",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "CPU utilization: user space usage",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(nodename) (irate(node_cpu_seconds_total{mode=\"user\"}[1m]) \n* on(instance) group_left(nodename) node_uname_info) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilization: system usage",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(nodename) (irate(node_cpu_seconds_total{mode=\"system\"}[1m]) \n* on(instance) group_left(nodename) node_uname_info) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilization: I/O wait",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(nodename) (irate(node_cpu_seconds_total{mode=\"iowait\"}[1m]) \n* on(instance) group_left(nodename) node_uname_info) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "GPU utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(Hostname) (DCGM_FI_DEV_GPU_UTIL)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}